version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 25
    rebase-strategy: "disabled"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
