import Header from "@/components/header";
import "./globals.css";
import { Inter } from "next/font/google";
import { Providers } from "@/store/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} min-w-screen min-h-screen`}>
        <Providers>
          <Header />
          <div className="body w-full h-full">{children}</div>
        </Providers>
      </body>
    </html>
  );
}
