import Header from "@/components/header";
import "./globals.css";
import { Inter } from "next/font/google";
import { Providers } from "@/store/provider";
import SessionWrapper from "@/components/session-wrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, session }: any) {
  return (
    <html lang="en">
      <body className={`${inter.className} min-w-screen min-h-screen`}>
        <Providers>
          <SessionWrapper>
            <Header />
            <div className="body w-full h-full">{children}</div>
          </SessionWrapper>
        </Providers>
      </body>
    </html>
  );
}
