on:
  pull_request:

name: Build and test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - uses: actions/checkout@v3

      # Install packages
      - run: npm install --frozen-lockfile --check-files

      # Lint
      - run: npm run lint

      # Build
      - run: npm run build
